- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - openstackclient-plugin-jobs
    check:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-python-barbicanclient-dsvm
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-python-barbicanclient-dsvm
